[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[context.production.environment]
  NODE_VERSION = "22.3.0"  # Or use any higher version compatible with Astro

[context.deploy-preview]
  NODE_VERSION = "22.3.0"  # Or use any higher version compatible with Astro
